//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "crates"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub homepage: Option<String>,
    pub analyzed: bool,
    pub download: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub version_new: String,
    pub download_failed: bool,
    pub version_handled: bool,
    pub compile_handled: bool,
    pub initial_compile_failed: bool,
    pub cargo_lock_exists: i32,
    pub heavy_deps_skipped: bool,
    pub heavy_deps_count: i32,
    pub dep_update_errors: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Homepage,
    Analyzed,
    Download,
    CreatedAt,
    UpdatedAt,
    VersionNew,
    DownloadFailed,
    VersionHandled,
    CompileHandled,
    InitialCompileFailed,
    CargoLockExists,
    HeavyDepsSkipped,
    HeavyDepsCount,
    DepUpdateErrors,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CrateVersionsIndex,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Homepage => ColumnType::String(StringLen::None).def().null(),
            Self::Analyzed => ColumnType::Boolean.def(),
            Self::Download => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::VersionNew => ColumnType::String(StringLen::None).def(),
            Self::DownloadFailed => ColumnType::Boolean.def(),
            Self::VersionHandled => ColumnType::Boolean.def(),
            Self::CompileHandled => ColumnType::Boolean.def(),
            Self::InitialCompileFailed => ColumnType::Boolean.def(),
            Self::CargoLockExists => ColumnType::Integer.def(),
            Self::HeavyDepsSkipped => ColumnType::Boolean.def(),
            Self::HeavyDepsCount => ColumnType::Integer.def(),
            Self::DepUpdateErrors => ColumnType::JsonBinary.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CrateVersionsIndex => {
                Entity::has_many(super::crate_versions_index::Entity).into()
            }
        }
    }
}

impl Related<super::crate_versions_index::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateVersionsIndex.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
