//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "crate_versions_index"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub crate_id: i32,
    pub version: String,
    pub deps: Json,
    pub features2: Option<Json>,
    pub pubtime: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CrateId,
    Version,
    Deps,
    Features2,
    Pubtime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Crates,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::CrateId => ColumnType::Integer.def(),
            Self::Version => ColumnType::String(StringLen::None).def(),
            Self::Deps => ColumnType::JsonBinary.def(),
            Self::Features2 => ColumnType::JsonBinary.def().null(),
            Self::Pubtime => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Crates => Entity::belongs_to(super::crates::Entity)
                .from(Column::CrateId)
                .to(super::crates::Column::Id)
                .into(),
        }
    }
}

impl Related<super::crates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Crates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
